version = 1

test_patterns = [
  "**/tests/**"
]

exclude_patterns = [
  "vendor/**",
  "**/examples/**"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "php"

[analyzers.meta]
  bootstrap_files = ["config/bootstrap.php"]
  skip_doc_coverage = ["class", "magic", "nonpublic"]

[[analyzers]]
name = "docker"

[[transformers]]
name = "php-cs-fixer"
