name: Build

on:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Build and Test
        uses: ./.github/workflows/reusable-build.yml
        secrets: inherit

    coverage:
        name: Coverage Reports
        needs: build
        uses: ./.github/workflows/reusable-coverage.yml
        secrets: inherit
