name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
  
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_extensions: sockets
          dev: no
          progress: yes

      - name: Run PHPUnit
        uses: php-actions/phpunit@v3
        with:
            php_extensions: "xdebug"
            coverage_cobertura: "coverage.xml"
