name: CI

on:
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build and Test
        uses: ./.github/workflows/reusable-build.yml
        secrets: inherit
        with:
            versioning: true

    coverage:
        name: Coverage Reports
        needs: build
        uses: ./.github/workflows/reusable-coverage.yml
        secrets: inherit

    release:
        name: Create Release
        needs: build
        runs-on: ubuntu-latest
        env:
            SEMVER: ${{ needs.build.outputs.semVer }}

        steps:
            - name: Create Release
              uses: ncipollo/release-action@v1.21.0
              with:
                  skipIfReleaseExists: true
                  allowUpdates: false
                  draft: false
                  makeLatest: true
                  tag: v${{ env.SEMVER }}
                  name: Release v${{ env.SEMVER }}
                  generateReleaseNotes: true
                  body: Release ${{ env.SEMVER }} of ${{ github.repository }}
